Run git svn fetch too.
git-svn-id: https://quirkysoft.googlecode.com/svn/branches/topics/gitscripts@702 89bda9af-7d2e-0410-a434-4dd01d8ab487

diff --git a/tools/git-svn-branch b/tools/git-svn-branch
--- a/tools/git-svn-branch
+++ b/tools/git-svn-branch
@@ -32,6 +32,12 @@ create_svn_branch()
     die "Could not create new branch in subversion"
 }
 
+git_svn_fetch()
+{
+  git svn fetch --all || die "Error fetching all git-svn branches"
+  git svn rebase --all || die "Error rebasing all git-svn branches"
+}
+
 update_svn()
 {
   # rebase a git topic branch on a new subversion branch
@@ -47,6 +53,10 @@ update_svn()
   if [ $? != 0 ] ; then
     exit 1
   fi
+  if [ "x$gitrev" == "x" ] ; then
+    # no revision, i.e. at master tip - use branch name
+    local gitrev=$branch
+  fi
   local svnrev=$(git svn find-rev $gitrev || die "Not a svn revision")
   if [ $? != 0 ] ; then
     exit 1
@@ -54,7 +64,7 @@ update_svn()
   # create a new svn topic branch
   create_svn_branch $safe_name $svnrev
   # pull the topic branch into git
-  git svn rebase --all || die "Error rebasing all git-svn branches"
+  git_svn_fetch
   # rebase the git topic branch onto the subversion branch
   git rebase --onto remotes/topics/$safe_name master $branch || die "Error rebasing $branch onto the subversion branch"
 }
@@ -70,7 +80,7 @@ new_in_svn()
     die "Error: Trunk not up to date, commit changes to subversion first."
   fi
   create_svn_branch $safe_name HEAD
-  git svn rebase --all || die "Error rebasing all git-svn branches"
+  git_svn_fetch
   git checkout -b $branch remotes/topics/$safe_name
 }
 
